### ISSUE TITLE
開発環境でローカルで立ち上げたAPIサーバに接続できない

### ISSUE THREAD

**Issue by urushiyama** [enpitut2017/Regi-Urico-client#10]
開発環境でAPIサーバとの連携をテストするためにローカルの別ポートにAPIサーバを立ち上げても、
APIサーバ側のポートで受けるべき通信（GET [/events/]など）がjsサーバ側への通信として処理され、結果としてRegisterのリストが読み込めない。

**Comment by kajyuuen** [comment]
ReactでURLのルートを相対参照で書いてたりしないですか？
例えば`/events`みたいな感じで．

本番だとドメインが同じだから大丈夫だけど，開発環境だと別ポートなので絶対参照じゃないと行かない気がする．

例
```
http://localhost:3001/events
```

**Comment by kajyuuen** [comment]
で昔これに遭遇したときの対処方法として，BASE_URLを設定していた気がする．
相対参照だと仮にAPIとクライアントが別IPになったときに対処できなかったり，今回みたいな例があるので意外と面倒だったりする．

**Comment by kajyuuen** [comment]
@urushiyama

**Comment by urushiyama** [comment]
@kajyuuen  全くその通りで、#11 で修正しました。

**Comment by kajyuuen** [comment]
@urushiyama 
プルリク気づきませんでした...

こういう方法でプルリクとイシューを紐付けるという技があったりする．
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by urushiyama** [comment]
@kajyuuen 返信が遅くなってしまい申し訳ありません。
紐付けはしてます。が、この方法ではIssue側にはreferencedがつかないんですかね？API側でもreferenceはPull Request側にしか表示されてなかったです。
Pull Requestを出したらIssue側にコメントするなどの対応が必要かもしれませんね。

**Comment by kajyuuen** [comment]
@urushiyama 

他のリポジトリを見た感じだと，プルリクを送るときにコメントで言及してればやってくれるっぽいですな

このIssueとかそんな感じだし．
https://github.com/pytorch/pytorch/issues/2001

<img width="758" alt="2017-12-01 1 33 19" src="https://user-images.githubusercontent.com/15792784/33442108-a45ef6c8-d637-11e7-92d1-f2c946e870d4.png">

こんな感じで表示されそう

**Comment by urushiyama** [comment]
@kajyuuen 
なるほど。逆にkajyuuenさんの貼ったリンクの効果でリンク先にreferenced通知されてますね。コメントからリンク消したほうが良いのでは？

**Comment by kajyuuen** [comment]
やっべ，やらかした
