### ISSUE TITLE
新規ユーザーを作成すると、イベント作成画面が一瞬だけ表示されて、画面が真っ白になってしまう

### ISSUE THREAD

**Issue by shuuji3** [enpitut2017/Regi-Urico-client#60]
ローカルでは正しく動作するのに、http://regi-urico.duckdns.org では動きません。
Google ChromeでもFirefoxでも同じです。
<img width="551" alt="2017-12-17 0 08 46" src="https://user-images.githubusercontent.com/1425259/34071745-906e805a-e2be-11e7-98e6-01a660f11cbe.png">

**Comment by kajyuuen** [comment]
ドメインがダメそう，
IPでアクセスする必要があるのでは？

**Comment by shuuji3** [comment]
いや、`/api/event/` へのリクエストは成功しているので、この問題はReactのレンダリングに原因があるのではないかと思います。
<img width="570" alt="2017-12-17 0 21 36" src="https://user-images.githubusercontent.com/1425259/34071832-53eb9698-e2c0-11e7-8a37-c527c72bd858.png">

**Comment by shuuji3** [comment]
ローカルでは正しく動作するというのは間違いでした。どうやらリダイレクトループが発生しているようです。これは前にもあった問題でしょうか？

<img width="456" alt="2017-12-17 18 26 49" src="https://user-images.githubusercontent.com/1425259/34078161-ea184444-e357-11e7-99d4-76fc803666dc.png">

<img width="932" alt="2017-12-17 18 03 22" src="https://user-images.githubusercontent.com/1425259/34077998-af85734a-e354-11e7-94b7-70c043ef8765.png">
