### ISSUE TITLE
商品名に絵文字を使うとエラーが発生する

### ISSUE THREAD

**Issue by shuuji3** [enpitut2017/Regi-Urico-client#63]
MySQLの設定を変更すると絵文字も使えるようになるらしいです。

RailsとMySQLでiOSの絵文字に対応(UTF8MB4化)した話
http://akataworks.hatenadiary.jp/entry/2016/02/26/102439

**Comment by urushiyama** [comment]
これはClientアプリ側で何か対応が必要なバグですか？

**Comment by shuuji3** [comment]
すみません、書く場所を間違えました。api側の問題です。
