### ISSUE TITLE
全商品の個数が0でもお支払ボタンが機能する

### ISSUE THREAD

**Issue by urushiyama** [enpitut2017/Regi-Urico-client#9]
Registerで、全ての商品の個数が0個でもお支払ボタンが機能し、「お会計：0円」と表示される。

**Comment by kajyuuen** [comment]
全ての商品の個数が0個だった場合にはお会計ボタンが押せないのが自然なUIっぽい感じしますがどう思いますか？

**Comment by kajyuuen** [comment]
@urushiyama

**Comment by urushiyama** [comment]
@kajyuuen そうするのが自然なUIだと思います。

**Comment by urushiyama** [comment]
これ思ったより根が深いな...diffCountをEventItemコンポーネントが個々に管理してるからRegisterから値読むのに何層もstateをLift Upするか、コールバックをput down(?)しないといけない。
